name: Run Unit Tests

on:
  pull_request:
    branches:
      - master
      - develop 
  push:
    branches:
      - master
      - develop
jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x 

    - name: Restore dependencies
      run: dotnet restore src/FakeStore.sln.sln

    - name: Run tests
      run: dotnet test src/Tests/FakeStore.UnitTests/FakeStore.UnitTests.csproj --verbosity normal
