version: '3.8'

services:
  fakestore-app:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - "80:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development" 
    restart: always